--- a/.github/workflows/ci-typescript.yml
+++ b/.github/workflows/ci-typescript.yml
@@ -20,4 +20,4 @@
           repository: sqlc-dev/sqlc-gen-typescript
           path: typescript
       - run: sqlc diff
-        working-directory: typescript/examples
+        working-directory: typescript/examples